### ISSUE TITLE
Create Issue is not working 

### ISSUE THREAD

**Issue by UmeshRajani** [taskadapter/redmine-java-api#287]
This is generated json:
`"{"issue":{"subject":"This is the first issue from osgi container","priority_id":3,"tracker_id":1,"description":"This is the first issue from osgi container"}}"`

This throws following exception:

```
com.taskadapter.redmineapi.NotFoundException: Server returned '404 not found'. response body: 
	at com.taskadapter.redmineapi.internal.comm.redmine.RedmineErrorHandler.processContent(RedmineErrorHandler.java:48)
	at com.taskadapter.redmineapi.internal.comm.redmine.RedmineErrorHandler.processContent(RedmineErrorHandler.java:22)
	at com.taskadapter.redmineapi.internal.comm.ComposingHandler.processContent(ComposingHandler.java:25)
	at com.taskadapter.redmineapi.internal.comm.ComposingHandler.processContent(ComposingHandler.java:25)
	at com.taskadapter.redmineapi.internal.comm.BaseCommunicator.sendRequest(BaseCommunicator.java:47)
	at com.taskadapter.redmineapi.internal.comm.redmine.RedmineAuthenticator.sendRequest(RedmineAuthenticator.java:52)
	at com.taskadapter.redmineapi.internal.comm.FmapCommunicator.sendRequest(FmapCommunicator.java:26)
	at com.taskadapter.redmineapi.internal.comm.FmapCommunicator.sendRequest(FmapCommunicator.java:26)
	at com.taskadapter.redmineapi.internal.comm.BasicSimplifier.sendRequest(BasicSimplifier.java:24)
	at com.taskadapter.redmineapi.internal.Transport.send(Transport.java:590)
	at com.taskadapter.redmineapi.internal.Transport.addObject(Transport.java:229)
	at com.taskadapter.redmineapi.IssueManager.createIssue(IssueManager.java:155)

```
Used redmine:
  Redmine version                2.6.0.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.19

redmine-java-api
 3.0.0

**Comment by alexeyOnGitHub** [comment]
please make sure your have REST API enabled in your server.
